[build-system]
requires = ["setuptools>=61.2", "setuptools_scm[toml]>=7.0.5"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
name = "miko-tasker"
authors = [
    {email = "scottryuu@outlook.com"},
    {name = "Cloudac7"}
]

description = "Analyzing tool for Deep Potential based chemical research."
readme = "README.md"
requires-python = ">=3.7"
license = {text = "Apache License, Version 2.0"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "ase",
    "click",
    "dscribe",
    "dpdata",
    "dpdispatcher>=0.4.15",
    "dpgen>=0.10.6",
    "dynaconf",
    "numpy",
    "pymatgen"
]
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-datadir",
    "coverage",
    "coveralls"
]

[project.urls]
repository = "https://github.com/cloudac7/miko-tasker"

[project.entry-points."miko.cmdline"]
tasker_cli = "miko_tasker.cmdline.tasker:tasker_cli"