name: Build and publish python package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
